import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "../styles/globals.scss";
import "../styles/main.scss";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hiring Management Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logogram.png" type="image/x-icon" />
      </head>
      <body className={`${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
